[package]
name = "Find_The_Imposter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
colored = "2.0"
prettytable-rs = "^0.10"
ansi_term = "0.12"

[lib]
name = "Find_The_Imposter" 